# Compose individual - Solo para referencia didactica
# Requiere que la base de datos este levantada (red_app debe existir)
# Para levantar el backend como parte del proyecto, usar los compose de la raiz

services:
  backend:
    build: .
    container_name: backend
    ports:
#      - "${BACKEND_PORT_EXTERNAL}:${BACKEND_PORT_INTERNAL}"
      - "8000:8000"
    env_file:
      - .env
    networks:
#      - red_app
      - red_postgres

networks:
#  red_app:
#    external: true
  red_postgres:
    external: true
