# Imagen Oficial de PostgreSQL
FROM postgres:16

# Establecemos la variable de entorno para evitar mensajes interactivos
ENV DEBIAN_FRONTEND = noninteractive

# Exponemos el puerto por defecto de PostgreSQL (Interno)
EXPOSE 5432

# Comando por defecto para ejecutar PostgreSQL
CMD ["postgres"]